data_dir: data/midi
cache_dir: data/cache
seq_len: 512
stride: 256
min_len: 32
instrument_program: null  # if set, restrict to a specific program
quantization:
  base_time_ms: 20
  steps_per_bar: 64
  velocity_bins: 32
  max_duration_steps: 128

